### ISSUE TITLE
It don't show  the  information

### ISSUE THREAD

**Issue by ingbrandon** [JonnyBGod/react-native-eventsource#19]
Hi @JonnyBGod , I have been working  sse with 'spring boot' and 'react native' and I find that the information data is not displayed, when I check the search package 'EventSource.js' that I find in funtion_registerEvents in specific' DeviceEventEmitter .addListener ('eventsourceEvent', 'you send ev.message instead of sen ev.data when i do it  this change all working and can show information data,  will  can you do this change ?

before
 var event = new EventSourceEvent(ev.type, {
          data: ev.message
});

after 
 var event = new EventSourceEvent(ev.type, {
        data: ev.data
});

thanks , for your time , good day.

**Comment by JonnyBGod** [comment]
Hi, sorry I don't use this library for years now and don't have the bandwidth to maintain it at the moment.

If you want to make changes and take over I can give you access.

**Comment by ingbrandon** [comment]
@JonnyBGod , great !  i would like to work on the project , thanks.

**Comment by ingbrandon** [comment]
> Hi, sorry I don't use this library for years now and don't have the bandwidth to maintain it at the moment.
> 
> If you want to make changes and take over I can give you access.

**Comment by ingbrandon** [comment]
@JonnyBGod  , sorry  men , could you give me access to the project ?

**Comment by JonnyBGod** [comment]
You should have receive an invitation. Check your notifications.
